server:
 port: 8083

spring:
  application:
    name: e-learning-microservice-rest-3
  cloud:
    config:
      discovery:
        enabled: true
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/