server:
 port: ${vcap.application.port:8888}
 
spring:
  cloud:
    config:
      server:
        uri: ${conf:https://github.com/gustavoorsi/e-learning-spring-config-properties}
        
eureka:
 client:
  serviceUrl:
   defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:9090}/eureka/